# These are supported funding model platforms

custom: ['http://blog.renatolucena.net/', 'https://www.paypal.com/donate?token=_Qs_PvjBm-y1hwsJtZi42vrZ4lJ40YD7Onj135yXs1F6CSOqAyOhBK26lSAjzO3AKmEfkzHO1xD_1Sky', 'https://trakteer.id/cpdrenato']
